# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"I\n\x04User\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0e\n\x06userID\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\")\n\x12\x43reateUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"J\n\x11\x43reateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\x05\"\'\n\x14GetSingleUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\",\n\x15GetSingleUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"%\n\x12GetAllUsersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"+\n\x13GetAllUsersResponse\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"\x0c\n\nInputEmpty2\xb7\x01\n\x0bUserService\x12\x36\n\x0b\x43reateAdmin\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12>\n\rGetSingleUser\x12\x15.GetSingleUserRequest\x1a\x16.GetSingleUserResponse\x12\x30\n\x0bGetAllUsers\x12\x0b.InputEmpty\x1a\x14.GetAllUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=14
  _globals['_USER']._serialized_end=87
  _globals['_CREATEUSERRESPONSE']._serialized_start=89
  _globals['_CREATEUSERRESPONSE']._serialized_end=130
  _globals['_CREATEUSERREQUEST']._serialized_start=132
  _globals['_CREATEUSERREQUEST']._serialized_end=206
  _globals['_GETSINGLEUSERREQUEST']._serialized_start=208
  _globals['_GETSINGLEUSERREQUEST']._serialized_end=247
  _globals['_GETSINGLEUSERRESPONSE']._serialized_start=249
  _globals['_GETSINGLEUSERRESPONSE']._serialized_end=293
  _globals['_GETALLUSERSREQUEST']._serialized_start=295
  _globals['_GETALLUSERSREQUEST']._serialized_end=332
  _globals['_GETALLUSERSRESPONSE']._serialized_start=334
  _globals['_GETALLUSERSRESPONSE']._serialized_end=377
  _globals['_INPUTEMPTY']._serialized_start=379
  _globals['_INPUTEMPTY']._serialized_end=391
  _globals['_USERSERVICE']._serialized_start=394
  _globals['_USERSERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
